use_small_heuristics="Off"
fn_single_line = true
force_multiline_blocks = false
indent_style = "Block"
single_line_if_else_max_width=120
struct_lit_single_line = true
fn_call_width=120
chain_width=80
attr_fn_like_width=100
max_width=120
where_single_line=true
format_strings=true
