[package]
name = "shard-distr"
version = "0.1.0"
authors = ["云惺 <yunxing.cyx@taobao.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
lazy_static = "1.4.0"
